/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_liste_reclamation (void);
GtkWidget* create_Client_reclamation (void);
GtkWidget* create_administrateur_voit_la_reclamation_dun_client (void);
