/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Pay_1 (void);
GtkWidget* create_home_pay_his_1 (void);
GtkWidget* create_Historique_1 (void);
GtkWidget* create_Auth_1 (void);
GtkWidget* create_criation_1 (void);
GtkWidget* create_Pay_2 (void);
